### ISSUE TITLE
User can create bugs with the same name by adding spaces after the name update

### ISSUE THREAD

**Issue by WilliamsiNFINITE** [SamNzo/Bug-tracker-VariaMos#2]
User can create bugs with the same name by adding spaces after the name

![image](https://user-images.githubusercontent.com/91114817/178459753-66e768b1-1fd1-4e72-acb4-ae4b3a21cabd.png)

**Comment by SamNzo** [comment]
test comment

**Comment by SamNzo** [comment]
hello

**Comment by SamNzo** [comment]
yikes
